/**
 * @vitest-environment jsdom
 */

import { describe, it, expect, beforeEach } from 'vitest'
import { isAutoGeneratedId, cleanLabelText, extractContextLabel, calculateOrdinal, scoreResolver, FieldFingerprint } from '../utils/fieldUtils'

describe('fieldUtils', () => {
  describe('isAutoGeneratedId', () => {
    it('detects Quasar UUID format', () => {
      expect(isAutoGeneratedId('f_12345678-1234-1234-1234-123456789012')).toBe(true)
      expect(isAutoGeneratedId('f_36b3acab-f395-4035-a711-f0799f84a7d0')).toBe(true)
    })
    
    it('detects Vue/Vuetify format', () => {
      expect(isAutoGeneratedId('v-1234')).toBe(true)
      expect(isAutoGeneratedId('input-56')).toBe(true)
    })
    
    it('detects React useId format', () => {
      expect(isAutoGeneratedId(':r1a:')).toBe(true)
    })

    it('detects Element Plus format', () => {
      expect(isAutoGeneratedId('el-id-1234-5')).toBe(true)
    })

    it('detects HeadlessUI format', () => {
      expect(isAutoGeneratedId('headlessui-listbox-button-123')).toBe(true)
    })
    
    it('allows normal IDs', () => {
      expect(isAutoGeneratedId('email-input')).toBe(false)
      expect(isAutoGeneratedId('user_password')).toBe(false)
      expect(isAutoGeneratedId('submitBtn')).toBe(false)
    })
  })

  describe('cleanLabelText', () => {
    it('removes material icons ligatures from string', () => {
      expect(cleanLabelText('Provinsi arrow_drop_down')).toBe('Provinsi')
      expect(cleanLabelText('cancel Email')).toBe('Email')
    })
    
    it('removes extra whitespaces and newlines', () => {
      expect(cleanLabelText('  Select   \n Country  ')).toBe('Select Country')
    })
    
    it('removes visual elements from DOM node without altering original DOM', () => {
      const div = document.createElement('div')
      div.innerHTML = `
        <span class="q-field__label">
          Provinsi
          <i class="q-icon material-icons">arrow_drop_down</i>
        </span>
      `
      const labelEl = div.querySelector('.q-field__label') as HTMLElement
      expect(cleanLabelText(labelEl)).toBe('Provinsi')
      
      // Original DOM should not be altered
      expect(labelEl.querySelector('.q-icon')).not.toBeNull()
    })
  })

  describe('extractContextLabel', () => {
    beforeEach(() => {
      document.body.innerHTML = ''
    })

    it('extracts text from previous sibling', () => {
      document.body.innerHTML = `
        <div class="row">
          <div><b>Rumah Sakit Asal</b></div>
          <div class="form-control" id="target">
             <input type="text" />
          </div>
        </div>
      `
      const target = document.getElementById('target') as HTMLElement
      expect(extractContextLabel(target)).toBe('Rumah Sakit Asal')
    })

    it('extracts text from separated column in row', () => {
      document.body.innerHTML = `
        <div class="row">
          <div class="col-4">
            <b>ID Pasien</b>
          </div>
          <div class="col-8">
            <div class="some-wrapper">
               <label class="q-field" id="target">
                 <input />
               </label>
            </div>
          </div>
        </div>
      `
      const target = document.getElementById('target') as HTMLElement
      expect(extractContextLabel(target)).toBe('ID Pasien')
    })
  })

  describe('calculateOrdinal', () => {
    beforeEach(() => {
      document.body.innerHTML = ''
    })

    it('calculates ordinal for field root', () => {
      document.body.innerHTML = `
        <div id="form-container">
          <div class="q-field" id="field-1"></div>
          <div>Some text</div>
          <div class="q-field" id="field-2"></div>
        </div>
      `
      const field2 = document.getElementById('field-2') as HTMLElement
      const ordinal = calculateOrdinal(field2, document.body)
      
      expect(ordinal.index).toBe(1)
      expect(ordinal.total).toBe(2)
      expect(ordinal.containerKey).toBe('body')
    })
  })

  describe('scoreResolver', () => {
    beforeEach(() => {
      document.body.innerHTML = ''
    })

    it('resolves by score correctly', () => {
      document.body.innerHTML = `
        <input type="text" id="target-input" name="first_name" data-testid="fname" />
        <input type="text" id="f_1234" name="last_name" />
      `
      const c1 = document.getElementById('target-input') as HTMLElement
      const c2 = document.getElementById('f_1234') as HTMLElement
      
      const fingerprint: FieldFingerprint = {
        name: 'first_name',
        testId: 'fname'
      }
      
      const result = scoreResolver(fingerprint, [c1, c2])
      expect(result.el).toBe(c1)
      expect(result.ambiguous).toBe(false)
    })
    
    it('resolves by ordinal when ambiguous', () => {
      document.body.innerHTML = `
        <div class="q-field" name="test"></div>
        <div class="q-field" name="test"></div>
      `
      const fields = Array.from(document.querySelectorAll('.q-field')) as HTMLElement[]
      
      const fingerprint: FieldFingerprint = {
        name: 'test',
        ordinal: { index: 1, total: 2, containerKey: 'body' }
      }
      
      const result = scoreResolver(fingerprint, fields)
      expect(result.el).toBe(fields[1])
      expect(result.ambiguous).toBe(false)
    })
  })
})
