export function isAutoGeneratedId(id: string): boolean {
  if (!id) return false;

  const patterns = [
    // Quasar: f_uuid
    /^f_[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/,
    // React useId
    /^:r[a-zA-Z0-9]*:$/,
    // Vuetify
    /^v-[a-zA-Z0-9-]+$/,
    /^input-\d+$/,
    // Element Plus
    /^el-id-[a-zA-Z0-9-]+$/,
    // HeadlessUI
    /^headlessui-[a-zA-Z0-9-]+$/,
    // MUI
    /^mui-\d+$/
  ];

  for (const pattern of patterns) {
    if (pattern.test(id)) {
      return true;
    }
  }

  // Generic hex/hash check (e.g. >8 random chars)
  // But wait, the test says: `email-input` -> false
  // For now let's just stick to the specific framework patterns and maybe a generic hash if we need to.

  return false;
}

export function cleanLabelText(textOrEl: string | HTMLElement | null): string {
  if (!textOrEl) return '';

  let text = '';
  if (typeof textOrEl === 'string') {
    text = textOrEl;
  } else {
    // Clone to remove unwanted visual elements without modifying DOM
    const clone = textOrEl.cloneNode(true) as HTMLElement;
    
    // Remove icons and native input texts that shouldn't be part of label
    const removeSelectors = ['.q-icon', '.material-icons', '.q-field__native', '[aria-hidden="true"]'];
    removeSelectors.forEach(sel => {
      const els = clone.querySelectorAll(sel);
      els.forEach(e => e.parentNode?.removeChild(e));
    });
    
    text = clone.textContent || '';
  }

  // Remove common material icon ligatures
  const ligatures = [
    'arrow_drop_down',
    'arrow_drop_up',
    'cancel',
    'clear',
    'check'
  ];

  let cleaned = text;
  for (const ligature of ligatures) {
    cleaned = cleaned.replace(new RegExp(`\\b${ligature}\\b`, 'g'), '');
  }

  // Remove extra spaces and newlines
  return cleaned.replace(/\s+/g, ' ').trim();
}

export function extractContextLabel(el: HTMLElement): string {
  let current: HTMLElement | null = el;
  let depth = 0;
  
  while (current && depth < 6) {
    let prev = current.previousElementSibling as HTMLElement;
    while (prev) {
      // If it contains a form control, skip it
      if (prev.querySelector('input, select, textarea, .q-field')) {
        prev = prev.previousElementSibling as HTMLElement;
        continue;
      }
      
      let text = '';
      const specificLabel = prev.querySelector('b, strong, label, p');
      if (specificLabel && (specificLabel.textContent || '').trim().length > 0) {
        text = (specificLabel.textContent || '').trim();
      } else {
        text = (prev.textContent || '').trim();
      }
      
      if (text && text.length > 0 && text.length <= 80) {
        return cleanLabelText(text);
      }
      prev = prev.previousElementSibling as HTMLElement;
    }
    current = current.parentElement;
    depth++;
  }
  
  return '';
}

export function calculateOrdinal(fieldRoot: HTMLElement, formRoot: HTMLElement = document.body) {
  const tagName = fieldRoot.tagName.toLowerCase();
  
  // Find all similar field roots in the same container
  let selector = tagName;
  if (fieldRoot.classList.contains('q-field')) {
    selector = '.q-field';
  } else if (fieldRoot.getAttribute('role') === 'combobox') {
    selector = '[role="combobox"]';
  }
  
  const siblings = Array.from(formRoot.querySelectorAll(selector)) as HTMLElement[];
  // Filter out those that are auto-generated clones or something, though usually fine
  const index = siblings.indexOf(fieldRoot);
  
  return {
    index: index >= 0 ? index : 0,
    total: siblings.length,
    containerKey: formRoot.tagName.toLowerCase() + (formRoot.id ? `#${formRoot.id}` : '')
  };
}

export interface FieldFingerprint {
  kind?: string;
  name?: string;
  testId?: string;
  label?: string;
  contextLabel?: string;
  placeholder?: string;
  stableId?: string;
  ordinal?: {
    index: number;
    total: number;
    containerKey: string;
  };
}

export function scoreResolver(fingerprint: FieldFingerprint, candidates: HTMLElement[]): { el: HTMLElement | null; ambiguous: boolean; log: string } {
  let bestScore = -1;
  let bestCandidates: HTMLElement[] = [];
  let logStr = '';
  
  for (const candidate of candidates) {
    let score = 0;
    const innerInput = candidate.querySelector('input, textarea, select');
    const name = candidate.getAttribute('name') || innerInput?.getAttribute('name');
    const testId = candidate.getAttribute('data-testid') || candidate.getAttribute('data-cy') || innerInput?.getAttribute('data-testid') || innerInput?.getAttribute('data-cy');
    const ariaLabel = candidate.getAttribute('aria-label') || innerInput?.getAttribute('aria-label');
    const placeholder = candidate.getAttribute('placeholder') || innerInput?.getAttribute('placeholder');
    const id = candidate.id || innerInput?.id;
    
    // Extracted labels for candidate
    let cLabel = '';
    const qLabel = candidate.querySelector('.q-field__label');
    if (qLabel) cLabel = cleanLabelText(qLabel as HTMLElement);
    else if (candidate.closest('label')) cLabel = cleanLabelText(candidate.closest('label') as HTMLElement);
    
    const cContextLabel = extractContextLabel(candidate);
    
    if (fingerprint.stableId && fingerprint.stableId === id) score += 50;
    if (fingerprint.name && fingerprint.name === name) score += 40;
    if (fingerprint.testId && fingerprint.testId === testId) score += 40;
    
    if (fingerprint.label && fingerprint.label.toLowerCase() === cLabel.toLowerCase()) score += 30;
    if (fingerprint.label && ariaLabel && fingerprint.label.toLowerCase() === ariaLabel.toLowerCase()) score += 30;
    
    if (fingerprint.placeholder && fingerprint.placeholder === placeholder) score += 20;
    if (fingerprint.contextLabel && fingerprint.contextLabel.toLowerCase() === cContextLabel.toLowerCase()) score += 10;
    
    if (score > 0) {
      if (score > bestScore) {
        bestScore = score;
        bestCandidates = [candidate];
      } else if (score === bestScore) {
        bestCandidates.push(candidate);
      }
    }
  }
  
  logStr = `Max score: ${bestScore}. Found ${bestCandidates.length} candidates.`;
  
  if (bestCandidates.length === 1) {
    return { el: bestCandidates[0] || null, ambiguous: false, log: logStr };
  } else if (bestCandidates.length > 1 && fingerprint.ordinal) {
    // Try tie-breaking with ordinal
    const targetIndex = fingerprint.ordinal.index;
    for (const cand of bestCandidates) {
       const candOrdinal = calculateOrdinal(cand, document.body); // simplifying containerRoot
       if (candOrdinal.index === targetIndex) {
         return { el: cand, ambiguous: false, log: logStr + ' (Resolved by ordinal)' };
       }
    }
    return { el: null, ambiguous: true, log: logStr + ' (Ambiguous after ordinal check)' };
  } else if (bestCandidates.length === 0 && fingerprint.ordinal) {
    // Fallback entirely to ordinal if no attributes matched
    const targetIndex = fingerprint.ordinal.index;
    for (const cand of candidates) {
       const candOrdinal = calculateOrdinal(cand, document.body);
       if (candOrdinal.index === targetIndex) {
         return { el: cand, ambiguous: false, log: logStr + ' (Resolved by pure ordinal fallback)' };
       }
    }
  }
  
  return { el: null, ambiguous: bestCandidates.length > 1, log: logStr + ' (No match or ambiguous)' };
}
