export interface SavedFormField {
  id: string;
  name: string;
  testId: string;
  label: string;
  type: string;
  index: number;
  value: string;
  kind?: string;
  optionLabel?: string;
  optionValue?: string;
  modelValue?: any;
  selectors?: { type: string; value: string }[];
  formIndex?: number;
}

import { isAutoGeneratedId, cleanLabelText, extractContextLabel, calculateOrdinal } from './fieldUtils';
import type { FieldFingerprint } from './fieldUtils';
import { callVueRpc } from './vueRpc';
import { dlog } from './debug';

export const getSavedFormKey = (origin: string, pathname: string, hash: string = ''): string => {
  return `fillkit_saved_form_${origin}${pathname}${hash}`;
};

export const saveFormFields = async (origin: string, pathname: string, hash: string, fields: SavedFormField[]): Promise<void> => {
  const key = getSavedFormKey(origin, pathname, hash);
  await chrome.storage.local.set({ [key]: fields });
};

export const getSavedFormFields = async (origin: string, pathname: string, hash: string): Promise<SavedFormField[]> => {
  const key = getSavedFormKey(origin, pathname, hash);
  const data = await chrome.storage.local.get([key]);
  return data[key] || [];
};

export const extractFormFields = async (debugMode: boolean = false): Promise<SavedFormField[]> => {
  const forms = Array.from(document.querySelectorAll('form'));
  const rawInputs = Array.from(document.querySelectorAll<HTMLElement>('input, textarea, select, [role="combobox"], .q-select, .q-radio, .q-checkbox, .q-btn-toggle'));
  const fieldRoots = Array.from(new Set(rawInputs.map(el => {
    if (el.closest('.q-radio')) return el.closest('.q-radio') as HTMLElement;
    if (el.closest('.q-checkbox')) return el.closest('.q-checkbox') as HTMLElement;
    if (el.closest('.q-btn-toggle')) return el.closest('.q-btn-toggle') as HTMLElement;
    return el.closest('.q-field') as HTMLElement || el;
  })));
  
  const fields: SavedFormField[] = [];
  const { getAdapterForElement } = require('./fieldAdapters');
  
  if (debugMode) {
    console.groupCollapsed(`[Fillkit] Extract Form Session (${fieldRoots.length} total field roots detected)`);
    dlog('extractForm', 'info', `Starting extraction. Total field roots: ${fieldRoots.length}. Forms: ${forms.length}`);
  }
  let skipped = 0;
  
  for (let index = 0; index < fieldRoots.length; index++) {
    const element = fieldRoots[index];
    const inputForCheck = element.tagName.match(/INPUT|TEXTAREA|SELECT/) ? element : element.querySelector('input, textarea, select') || element;
    
    let isSkipped = false;
    if (element.classList.contains('q-field')) {
      if (element.classList.contains('q-field--disabled') || element.classList.contains('q-field--readonly')) {
        isSkipped = true;
      }
    } else {
      if ((inputForCheck as any).disabled || (inputForCheck as any).readOnly || (inputForCheck as any).type === 'hidden') {
        isSkipped = true;
      }
    }

    if (isSkipped) {
      if (debugMode) dlog('extractForm', 'warn', `Skipped field index ${index}: disabled, readonly or hidden`);
      skipped++;
      continue;
    }
    if ((inputForCheck as any).type === 'password') {
      if (debugMode) dlog('extractForm', 'warn', `Skipped field index ${index}: type password`);
      skipped++;
      continue;
    }


    const adapter = getAdapterForElement(element);
    if (!adapter) {
      if (debugMode) dlog('extractForm', 'warn', `Skipped field index ${index}: no adapter found`);
      skipped++;
      continue;
    }

    const readResult = adapter.read(element);
    if (!readResult) {
      if (debugMode) dlog('extractForm', 'warn', `Skipped field index ${index}: read returned empty`);
      skipped++;
      continue;
    }

    let valueStr = '';
    let optionLabel = '';
    let optionValue = '';
    
    if (typeof readResult === 'object' && !Array.isArray(readResult)) {
      const res = readResult as any;
      if (!res.value || (Array.isArray(res.value) && res.value.length === 0)) continue;
      valueStr = Array.isArray(res.value) ? res.value.join(',') : res.value;
      optionLabel = res.optionLabel ? (Array.isArray(res.optionLabel) ? res.optionLabel.join(',') : res.optionLabel) : '';
      optionValue = res.optionValue ? (Array.isArray(res.optionValue) ? res.optionValue.join(',') : res.optionValue) : '';
    } else {
      if (!readResult || (Array.isArray(readResult) && readResult.length === 0)) continue;
      valueStr = Array.isArray(readResult) ? readResult.join(',') : readResult;
    }

    let label = '';
    const labels = (element as any).labels;
    if (labels && labels.length > 0) {
      label = cleanLabelText(labels[0] as HTMLElement);
    } else {
      const parentLabel = element.closest('label');
      if (parentLabel && parentLabel !== element) {
        label = cleanLabelText(parentLabel as HTMLElement);
      }
    }
    
    // Quasar fallback label if inside a field
    if (!label) {
      const qLabel = element.querySelector('.q-field__label');
      if (qLabel) label = cleanLabelText(qLabel as HTMLElement);
    }

    const contextLabel = extractContextLabel(element);
    
    const selectors: { type: string; value: string }[] = [];
    
    // Find the primary identifiable input for attributes
    const attrNode = element.tagName.match(/INPUT|TEXTAREA|SELECT/) ? element : element.querySelector('input, textarea, select') || element;
    
    const testIdAttr = attrNode.getAttribute('data-testid') || attrNode.getAttribute('data-cy') || attrNode.getAttribute('data-test') || element.getAttribute('data-testid');
    if (testIdAttr) selectors.push({ type: 'testId', value: testIdAttr });
    
    const nameAttr = attrNode.getAttribute('name');
    if (nameAttr) selectors.push({ type: 'name', value: nameAttr });
    
    const idAttr = attrNode.id || element.id;
    let stableId = '';
    if (idAttr && !isAutoGeneratedId(idAttr)) {
      stableId = idAttr;
      selectors.push({ type: 'id', value: idAttr });
    }
    
    const ariaLabel = attrNode.getAttribute('aria-label') || element.getAttribute('aria-label');
    if (ariaLabel) selectors.push({ type: 'ariaLabel', value: ariaLabel });
    
    if (label) selectors.push({ type: 'label', value: label });
    
    const placeholder = attrNode.getAttribute('placeholder') || element.getAttribute('placeholder');
    if (placeholder) selectors.push({ type: 'placeholder', value: placeholder });
    
    const ordinal = calculateOrdinal(element, document.body);
    const closestForm = element.closest('form');
    const formIndex = closestForm ? forms.indexOf(closestForm) : -1;

    let modelValue: any = undefined;
    
    try {
      const originalId = element.id;
      const tempId = `fillr_temp_${Math.random().toString(36).substr(2, 9)}`;
      element.id = tempId;
      modelValue = await callVueRpc('GET_MODEL', tempId);
      if (originalId) {
        element.id = originalId;
      } else {
        element.removeAttribute('id');
      }
    } catch (err) {
      // Vue helper not injected or error
    }

    const savedField = {
      id: attrNode.id || element.id || '',
      name: nameAttr || '',
      testId: testIdAttr || '',
      label,
      type: attrNode.getAttribute('type') || attrNode.tagName.toLowerCase(),
      index,
      value: valueStr,
      kind: adapter.name,
      selectors,
      ...(optionLabel ? { optionLabel } : {}),
      ...(optionValue ? { optionValue } : {}),
      ...(modelValue !== undefined && modelValue !== null ? { modelValue } : {}),
      // new fingerprint fields
      ...(contextLabel ? { contextLabel } : {}),
      ...(placeholder ? { placeholder } : {}),
      ...(ariaLabel ? { ariaLabel } : {}),
      ...(stableId ? { stableId } : {}),
      ordinal,
      formIndex
    } as SavedFormField & FieldFingerprint;
    
    fields.push(savedField);
    
    if (debugMode) {
      dlog('extractForm', 'info', `Saved field index ${index}`, { 
        label, 
        stableId, 
        kind: adapter.name, 
        selectors: selectors.map(s => s.type) 
      });
    }
  }
  
  if (debugMode) {
    dlog('extractForm', 'info', `Extraction complete. Saved: ${fields.length}, Skipped: ${skipped}`);
    console.groupEnd();
  }
  
  return fields;
};
